<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork865-2023-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

<h1 align=center><font size = 5>Assignment: SQL Notebook for Peer Assignment</font></h1>

Estimated time needed: **60** minutes.

## Introduction
Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset  into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones. 

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage. 


Therefore if we can determine if the first stage will land, we can determine the cost of a launch. 

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

 <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv" target="_blank">Spacex DataSet</a>

**Navigate to the Go to UI screen** 

* Refer to this insruction in this <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sign%20up%20for%20IBM%20Cloud%20-%20Create%20Db2%20service%20instance%20-%20Get%20started%20with%20the%20Db2%20console/instructional-labs.md.html">link</a> for viewing  the   Go to UI screen. 


* Later click on **Data link(below SQL)**  in the Go to UI screen  and click on **Load Data** tab.  



* Later browse for the downloaded spacex file.



<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/browsefile.png" width="800">


* Once done select the schema andload the file.  


 <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/spacexload3.png" width="800">


If you are facing a problem in uploading the dataset (which is a csv file), you can follow the steps below to upload the .sql file instead of the CSV file:

* Download the file <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/Spacex%20.sql">Spacex.sql</a>

* Later click on **SQL** in the  **Go to UI Screen**.

* Use the **From file** option to browse for the **SQL** file and upload it.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/sqlfile.png">

* Once you upload the script,you can use the **Run All** option to run all the queries to insert the data.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/runall.png">

In [1]:
!pip install --force-reinstall ibm_db==3.1.0 ibm_db_sa==0.3.3
!pip install sqlalchemy==1.3.24
!pip uninstall ipython-sql -y
!pip install ipython-sql==0.4.1

Collecting ibm_db==3.1.0
  Using cached ibm_db-3.1.0.tar.gz (797 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Processing /Users/mararamosgomes/Library/Caches/pip/wheels/49/e6/22/d17191bb80f7517bb37be325d5d6c94808818d12b6aabc7d4e/ibm_db_sa-0.3.3-cp38-none-any.whl
Collecting sqlalchemy>=0.7.3
  Downloading SQLAlchemy-2.0.9-cp38-cp38-macosx_10_9_x86_64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 3.6 MB/s eta 0:00:01
Collecting typing-extensions>=4.2.0
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting greenlet!=0.4.17; platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32")))))
  Downloading greenlet-2.0.2-cp38-cp38-macosx_10_15_x86_64.whl (241 kB)
     |████████████████████████████████| 241 kB 2.3 MB/s eta 0:00:01
Building wheels for collected packages: ibm-db
  Building wheel for ibm-db (PEP 517) ... done
  Created wheel for ibm-db: filename=ibm_db-3.1.0-cp38-cp38-macosx_10_15_x86_64.whl size=32289293 sha256=e2216480d994d6921fbc21789d0de7d90afc2bb8061548c57712694a4df2871d
  Stored in directory: /Users/mararamosgomes/Library/Caches/pip/wheels/43/71/0a/3065745bc1dc4cafbdcb09e2557082609f7689b16108b670df
Successfully built ibm-db
Installing collected packages: ibm-db, typing-extensions, greenlet, sqlalchemy, ibm-db-sa
Successfully installed greenlet-2.0.2 ibm-db-3.1.0 ibm-db-sa-0.3.3 sqlalchemy-2.0.9 typing-extensions-4.5.0
Collecting sqlalchemy==1.3.24
  Downloading SQLAlchemy-1.3.24-cp38-cp38-macosx_10_14_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 3.9 MB/s eta 0:00:01
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.9
    Uninstalling SQLAlchemy-2.0.9:
      Successfully uninstalled SQLAlchemy-2.0.9
Successfully installed sqlalchemy-1.3.24
WARNING: Skipping ipython-sql as it is not installed.
Collecting ipython-sql==0.4.1
  Using cached ipython_sql-0.4.1-py3-none-any.whl (21 kB)
Collecting sqlparse
  Using cached sqlparse-0.4.4-py3-none-any.whl (41 kB)
Collecting prettytable<1
  Using cached prettytable-0.7.2.tar.bz2 (21 kB)
Requirement already satisfied: ipython>=1.0 in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from ipython-sql==0.4.1) (7.18.1)
Requirement already satisfied: six in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from ipython-sql==0.4.1) (1.15.0)
Requirement already satisfied: sqlalchemy>=0.6.7 in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from ipython-sql==0.4.1) (1.3.24)
Requirement already satisfied: ipython-genutils>=0.1.0 in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from ipython-sql==0.4.1) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (3.0.8)
Requirement already satisfied: jedi>=0.10 in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.15.2)
Requirement already satisfied: decorator in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (4.4.2)
Requirement already satisfied: traitlets>=4.2 in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (5.0.4)
Requirement already satisfied: setuptools>=18.5 in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (50.3.0.post20201006)
Requirement already satisfied: appnope; sys_platform == "darwin" in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.1.0)
Requirement already satisfied: pexpect>4.3; sys_platform != "win32" in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (4.8.0)
Requirement already satisfied: pygments in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (2.7.1)
Requirement already satisfied: pickleshare in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.7.5)
Requirement already satisfied: backcall in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.2.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=1.0->ipython-sql==0.4.1) (0.2.5)
Requirement already satisfied: parso>=0.5.2 in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from jedi>=0.10->ipython>=1.0->ipython-sql==0.4.1) (0.5.2)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/envs/spyder/lib/python3.8/site-packages (from pexpect>4.3; sys_platform != "win32"->ipython>=1.0->ipython-sql==0.4.1) (0.6.0)
Building wheels for collected packages: prettytable
  Building wheel for prettytable (setup.py) ... done
  Created wheel for prettytable: filename=prettytable-0.7.2-py3-none-any.whl size=13700 sha256=c7e761445657ce472f994bbbe962740257c586e1ca13328b7b9b3da33cf94835
  Stored in directory: /Users/mararamosgomes/Library/Caches/pip/wheels/46/60/6c/bb25d05df22906786206e901e9354bb3061061191116768bee
Successfully built prettytable
Installing collected packages: sqlparse, prettytable, ipython-sql
Successfully installed ipython-sql-0.4.1 prettytable-0.7.2 sqlparse-0.4.4

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [2]:
%load_ext sql




**DB2 magic in case of  UI service credentials.**



<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/servicecredentials.png" width="600">  

* Use the following format.

* Add security=SSL at the end

**%sql ibm_db_sa://my-username:my-password@my-hostname:my-port/my-db-name?security=SSL**

In [3]:
%sql ibm_db_sa://ghf44242:5lGAcVnCoU7MWaJN@125f9f61-9715-46f9-9399-c8177b21803b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:30426/bludb?security=SSL

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])
dlopen(/opt/anaconda3/envs/spyder/lib/python3.8/site-packages/ibm_db.cpython-38-darwin.so, 0x0002): Symbol not found: (___cxa_throw_bad_array_new_length)
  Referenced from: '/opt/anaconda3/envs/spyder/lib/python3.8/site-packages/clidriver/lib/libdb2.dylib'
  Expected in: '/usr/lib/libstdc++.6.dylib'
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

### Task 1




##### Display the names of the unique launch sites  in the space mission

In [ ]:
# Display the names of the unique launch sites  in the space mission
%sql select distinct(LAUNCH_SITE) from SPACEXTBL


### Task 2


#####  Display 5 records where launch sites begin with the string 'CCA'

In [ ]:
# Display 5 records where launch sites begin with the string 'CCA'
%sql select * from SPACEXTBL where LAUNCH_SITE like 'CCA%' limit 5

### Task 3




##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [ ]:
# Display the total payload mass carried by boosters launched by NASA (CRS)
%sql select sum(payload_mass__kg_) from SPACEXTBL where CUSTOMER = 'NASA (CRS)'

### Task 4




##### Display average payload mass carried by booster version F9 v1.1

In [ ]:
# Display average payload mass carried by booster version F9 v1.1
%sql select avg(payload_mass__kg_) from SPACEXTBL where BOOSTER_VERSION = 'F9 v1.1'

### Task 5

##### List the date when the first successful landing outcome in ground pad was acheived.


_Hint:Use min function_

In [6]:
# remove white spaces from column name for further analysis

# List the date when the first succesful landing outcome in ground pad was acheived.
%sql select min(DATE) from SPACEXTBL where LANDING__OUTCOME = 'Success (ground pad)'

Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

### Task 6

##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000

In [ ]:
# List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000
%sql select distinct(BOOSTER_VERSION) from SPACEXTBL where LANDING__OUTCOME = 'Success (drone ship)' and payload_mass__kg_ > 4000 and payload_mass__kg_ < 6000

### Task 7




##### List the total number of successful and failure mission outcomes

In [ ]:
# List the total number of successful and failure mission outcomes
%sql select MISSION_OUTCOME, count(MISSION_OUTCOME) from SPACEXTBL group by MISSION_OUTCOME

### Task 8



##### List the   names of the booster_versions which have carried the maximum payload mass. Use a subquery

In [ ]:
# List the names of the booster_versions which have carried the maximum payload mass. Use a subquery
%sql select distinct(BOOSTER_VERSION) from SPACEXTBL where payload_mass__kg_ = (select max(payload_mass__kg_) from SPACEXTBL)

### Task 9


##### List the failed landing_outcomes in drone ship, their booster versions, and launch site names for in year 2015

In [ ]:
# List the records which will display the month names, failure landing_outcomes in drone ship ,booster versions, launch_site for the months in year 2015. Use sql lite
%sql select strftime('%m',DATE), LANDING__OUTCOME, BOOSTER_VERSION, LAUNCH_SITE from SPACEXTBL where strftime('%Y',DATE) = '2015' and LANDING__OUTCOME = 'Failure (drone ship)'

### Task 10

##### Rank the count of landing outcomes (such as Failure (drone ship) or Success (ground pad)) between the date 2010-06-04 and 2017-03-20, in descending order

In [ ]:
# Rank the count of successful landing_outcomes between the date 04-06-2010 and 20-03-2017 in descending order.¶
%sql select LANDING__OUTCOME, count(LANDING__OUTCOME) from SPACEXTBL where DATE between '2010-06-04' and '2017-03-20' group by LANDING__OUTCOME order by count(LANDING__OUTCOME) desc

### Reference Links

* <a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20String%20Patterns%20-%20Sorting%20-%20Grouping/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : String Patterns, Sorting and Grouping</a>  

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Built-in%20functions%20/Hands-on_Lab__Built-in_Functions.md.html?origin=www.coursera.org">Hands-on Lab: Built-in functions</a>

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sub-queries%20and%20Nested%20SELECTs%20/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : Sub-queries and Nested SELECT Statements</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-3-SQLmagic.ipynb">Hands-on Tutorial: Accessing Databases with SQL magic</a>

*  <a href= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing.ipynb">Hands-on Lab: Analyzing a real World Data Set</a>

## Author(s)

<h4> Lakshmi Holla </h4>

## Other Contributors

<h4> Rav Ahuja </h4>

## Change log
| Date | Version | Changed by | Change Description |
|------|--------|--------|---------|
| 2021-10-12 | 0.4 |Lakshmi Holla | Changed markdown|
| 2021-08-24 | 0.3 |Lakshmi Holla | Added library update|
| 2021-07-09 | 0.2 |Lakshmi Holla | Changes made in magic sql|
| 2021-05-20 | 0.1 |Lakshmi Holla | Created Initial Version |

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>